version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file: ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
  db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DATABASE_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - WEBAPP_URL=${WEBAPP_URL}
      - API_DOMAIN=${API_DOMAIN}
      - API_ACCESS_TOKEN_EXPIRATION_MS=${API_ACCESS_TOKEN_EXPIRATION_MS}
      - API_REFRESH_TOKEN_EXPIRATION_MS=${API_REFRESH_TOKEN_EXPIRATION_MS}
      - API_EMAIL_VERIFICATION_TOKEN_EXPIRATION_MS=${API_EMAIL_VERIFICATION_TOKEN_EXPIRATION_MS}
      - SENDGRID_SENDER_EMAIL=${SENDGRID_SENDER_EMAIL}
      - SENDGRID_APIKEY=${SENDGRID_APIKEY}
      - SENDGRID_VERIFY_EMAIL_TEMPLATE_ID=${SENDGRID_VERIFY_EMAIL_TEMPLATE_ID}
      - SENDGRID_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID=${SENDGRID_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID}
      - EASYPOST_APIKEY=${EASYPOST_APIKEY}
      - EASYPOST_WEBHOOK_ENDPOINT_SECRET=${EASYPOST_WEBHOOK_ENDPOINT_SECRET}
      - EASYPOST_WEBHOOK_ENDPOINT_URL=${EASYPOST_WEBHOOK_ENDPOINT_URL}
      - EASYPOST_CREATE_WEBHOOK=${EASYPOST_CREATE_WEBHOOK}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_APIKEY=${STRIPE_APIKEY}
      - STRIPE_WEBHOOK_ENDPOINT_SECRET=${STRIPE_WEBHOOK_ENDPOINT_SECRET}
