version: "3.8"
services:
  db:
    image: postgres
    platform: linux/x86_64 # necessary when ran on Mac M1
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - "5432:5432"