version: "3.8"
services:
  db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  api:
    image: ghcr.io/polairelabs/navaship:latest
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DATABASE_PORT}/${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - WEBAPP_URL=${WEBAPP_URL}
      - API_DOMAIN=${API_DOMAIN}
      - SENDGRID_SENDER_EMAIL=${SENDGRID_SENDER_EMAIL}
      - SENDGRID_APIKEY=${SENDGRID_APIKEY}
      - SENDGRID_VERIFY_EMAIL_TEMPLATE_ID=${SENDGRID_VERIFY_EMAIL_TEMPLATE_ID}
      - SENDGRID_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID=${SENDGRID_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID}
      - EASYPOST_APIKEY=${EASYPOST_APIKEY}
      - EASYPOST_WEBHOOK_ENDPOINT_SECRET=${EASYPOST_WEBHOOK_ENDPOINT_SECRET}
      - EASYPOST_WEBHOOK_ENDPOINT_URL=${EASYPOST_WEBHOOK_ENDPOINT_URL}
      - STRIPE_APIKEY=${STRIPE_APIKEY}
      - STRIPE_WEBHOOK_ENDPOINT_SECRET=${STRIPE_WEBHOOK_ENDPOINT_SECRET}
    command: [ "./wait-for-it.sh", "db:${DATABASE_PORT}", "--timeout=60", "java -jar target/api.jar" ]
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
