version: "3.8"
services:
  db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  api:
    image: ghcr.io/polairelabs/navaship:latest
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DATABASE_PORT}/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - WEBAPP_URL=${WEBAPP_URL}
      - API_DOMAIN=${API_DOMAIN}
      - API_ACCESS_TOKEN_EXPIRATION_MS=${API_ACCESS_TOKEN_EXPIRATION_MS}
      - API_REFRESH_TOKEN_EXPIRATION_MS=${API_REFRESH_TOKEN_EXPIRATION_MS}
      - API_EMAIL_VERIFICATION_TOKEN_EXPIRATION_MS=${API_EMAIL_VERIFICATION_TOKEN_EXPIRATION_MS}
      - SENDGRID_SENDER_EMAIL=${SENDGRID_SENDER_EMAIL}
      - SENDGRID_APIKEY=${SENDGRID_APIKEY}
      - SENDGRID_VERIFY_EMAIL_TEMPLATE_ID=${SENDGRID_VERIFY_EMAIL_TEMPLATE_ID}
      - SENDGRID_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID=${SENDGRID_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID}
      - EASYPOST_APIKEY=${EASYPOST_APIKEY}
      - EASYPOST_WEBHOOK_ENDPOINT_SECRET=${EASYPOST_WEBHOOK_ENDPOINT_SECRET}
      - EASYPOST_WEBHOOK_ENDPOINT_URL=${EASYPOST_WEBHOOK_ENDPOINT_URL}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_APIKEY=${STRIPE_APIKEY}
      - STRIPE_WEBHOOK_ENDPOINT_SECRET=${STRIPE_WEBHOOK_ENDPOINT_SECRET}
