name: Continuous Deployment. Deploy API to VPS

# Change to PR to release once pipeline is stable
on:
  push:
    branches:
      - release

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          # This will create a directory named `api` and copy the repo contents to it
          # so that you can easily upload it to your remote server
          path: api
          ref: release

      - name: Copy repo to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.VPS_HOST }}
          port: ${{ vars.VPS_PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: api
          target: "~/navaship"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.VPS_HOST }}
          port: ${{ vars.VPS_PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/navaship/api
            export DATABASE_PORT="${{ vars.DATABASE_PORT }}"
            export DATABASE_NAME="${{ vars.DATABASE_NAME }}"
            export DATABASE_USER="${{ secrets.DATABASE_USER }}"
            export DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}"
            export API_PORT="${{ vars.API_PORT }}"
            export API_DOMAIN="${{ vars.API_DOMAIN }}"
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose -f docker-compose.prod.yml up -d
            
