name: Continuous Deployment

on:
  push:
    branches:
      - release

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          # This will create a directory named `api` and copy the repo contents to it
          # so that you can easily upload it to your remote server
          path: api
          ref: release

      - name: Copy repo to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.VPS_HOST }}
          port: ${{ vars.VPS_PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: api
          target: "~/navaship"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.VPS_HOST }}
          port: ${{ vars.VPS_PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/navaship/api
            docker-compose -f docker-compose.prod.yml down
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            export SPRING_PROFILES_ACTIVE="prod"
            export DATABASE_NAME="${{ vars.DATABASE_NAME }}"
            export DATABASE_USER="${{ vars.DATABASE_USER }}"
            export DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}"
            export API_PORT="${{ vars.API_PORT }}"
            export API_DOMAIN="${{ vars.API_DOMAIN }}"
            export WEBAPP_URL="${{ vars.WEBAPP_URL }}"
            export SENDGRID_SENDER_EMAIL="${{ vars.SENDGRID_SENDER_EMAIL }}"
            export SENDGRID_APIKEY="${{ secrets.SENDGRID_APIKEY }}"
            export EASYPOST_APIKEY="${{ secrets.EASYPOST_APIKEY }}"
            export EASYPOST_WEBHOOK_ENDPOINT_SECRET="${{ secrets.EASYPOST_WEBHOOK_ENDPOINT_SECRET }}"
            export EASYPOST_WEBHOOK_ENDPOINT_URL="${{ vars.EASYPOST_WEBHOOK_ENDPOINT_URL }}"
            export STRIPE_APIKEY="${{ secrets.STRIPE_APIKEY }}"
            export STRIPE_WEBHOOK_ENDPOINT_SECRET="${{ secrets.STRIPE_WEBHOOK_ENDPOINT_SECRET }}"
            export STRIPE_PRODUCT_ID="${{ vars.STRIPE_PRODUCT_ID }}"
            export AUTH_PRIVATE_KEY="${{ secrets.AUTH_PRIVATE_KEY }}"
            export AUTH_PUBLIC_KEY="${{ secrets.AUTH_PUBLIC_KEY }}"
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
