name: Continuous Deployment. Deploy API to VPS

# Change to PR to release once pipeline is stable
on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout the repo
#        uses: actions/checkout@v2
#        with:
#          # This will create a directory named `my-repo` and copy the repo contents to it
#          # so that you can easily upload it to your remote server
#          path: navaship-api-repo

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/navaship
            git clone https://github.com/polairelabs/NavaShip
            
