name: Continuous Deployment. Deploy API to VPS

# Change to PR to release once pipeline is stable
on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          # This will create a directory named `api-repo` and copy the repo contents to it
          # so that you can easily upload it to your remote server
          path: api-repo

#      - name: Copy repo to remote server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          port: ${{ secrets.port }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          passphrase: ${{ secrets.PASSPHRASE }}
#          source: my-repo
#          target: "~/navaship"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            scp -o StrictHostKeyChecking=no -r api-repo ~/navaship
            cd ~/navaship/api
            cat docker-compose.dev.yml
