name: Continuous Deployment. Deploy API to VPS

on:
  push:
    branches:
      - release

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout the repo
        uses: actions/setup-java@v2
        with:
          # This will create a directory named `api` and copy the repo contents to it
          # so that you can easily upload it to your remote server
          path: api
          ref: release
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Generate the package
        run: mvn -B package --file pom.xml

      - name: Copy repo to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.VPS_HOST }}
          port: ${{ vars.VPS_PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: api
          target: "~/navaship"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.VPS_HOST }}
          port: ${{ vars.VPS_PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/navaship/api
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            DATABASE_PORT="${{ vars.DATABASE_PORT }}" \
            DATABASE_NAME="${{ vars.DATABASE_NAME }}" \
            DATABASE_USER="${{ secrets.DATABASE_USER }}" \
            DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
            API_PORT="${{ vars.API_PORT }}" \
            API_DOMAIN="${{ vars.API_DOMAIN }}" \
            docker-compose -f docker-compose.prod.yml up -d
